import type { Config } from 'tailwindcss'
import forms from '@tailwindcss/forms'
import containerQueries from '@tailwindcss/container-queries'

export default {
  content: ['./inertia/**/*.vue', './resources/views/**/*.edge'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f3faff',
        'surface': '#f3faff',
        'inverse-on-surface': '#dff4ff',
        'surface-variant': '#cfe6f2',
        'secondary-fixed-dim': '#fabd00',
        'primary-container': '#1a237e',
        'on-error': '#ffffff',
        'outline-variant': '#c6c5d4',
        'on-tertiary-fixed-variant': '#065043',
        'surface-container-high': '#d5ecf8',
        'on-background': '#071e27',
        'surface-container-low': '#e6f6ff',
        'on-secondary-container': '#6c5000',
        'primary-fixed-dim': '#bdc2ff',
        'secondary-fixed': '#ffdf9e',
        'on-surface-variant': '#454652',
        'on-tertiary': '#ffffff',
        'surface-container': '#dbf1fe',
        'secondary-container': '#fdc003',
        'outline': '#767683',
        'surface-tint': '#4c56af',
        'on-tertiary-fixed': '#00201a',
        'inverse-primary': '#bdc2ff',
        'on-secondary': '#ffffff',
        'tertiary-fixed': '#afefdd',
        'on-primary-container': '#8690ee',
        'surface-container-lowest': '#ffffff',
        'primary-fixed': '#e0e0ff',
        'on-primary-fixed-variant': '#343d96',
        'on-primary-fixed': '#000767',
        'background': '#f3faff',
        'tertiary-container': '#00372d',
        'secondary': '#785900',
        'on-secondary-fixed': '#261a00',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'inverse-surface': '#1e333c',
        'tertiary-fixed-dim': '#94d3c1',
        'success': '#10b981',
        'on-success': '#ffffff',
        'success-container': '#d1fae5',
        'on-success-container': '#065f46',
        'surface-dim': '#c7dde9',
        'on-secondary-fixed-variant': '#5b4300',
        'surface-container-highest': '#cfe6f2',
        'primary': '#000666',
        'on-surface': '#071e27',
        'tertiary': '#002019',
        'error': '#ba1a1a',
        'on-tertiary-container': '#65a393',
        'on-error-container': '#93000a',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      fontFamily: {
        headline: ['Public Sans', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
    },
  },
  plugins: [forms, containerQueries],
} satisfies Config
