/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  admin: {
    Graduation: () => import('#controllers/admin/graduation_controller'),
    Interviews: () => import('#controllers/admin/interviews_controller'),
    Majors: () => import('#controllers/admin/majors_controller'),
    Settings: () => import('#controllers/admin/settings_controller'),
    Users: () => import('#controllers/admin/users_controller'),
  },
  GraduationCheck: () => import('#controllers/graduation_check_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Session: () => import('#controllers/session_controller'),
}
