/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class InterviewSchema extends BaseModel {
  static $columns = ['academicScore', 'accompaniment', 'attitudeScore', 'billingDetails', 'characterAnswers', 'createdAt', 'emergencyContact', 'id', 'infoSource', 'interviewDate', 'interviewer', 'livingWith', 'longTermGoals', 'majorChoice', 'notes', 'parentCommitments', 'reasonChoosingSchool', 'schoolOrigin', 'specialActivities', 'status', 'studentName', 'technicalScore', 'totalScore', 'updatedAt', 'userId', 'violationAgreement'] as const
  $columns = InterviewSchema.$columns
  @column()
  declare academicScore: number | null
  @column()
  declare accompaniment: string | null
  @column()
  declare attitudeScore: number | null
  @column()
  declare billingDetails: any | null
  @column()
  declare characterAnswers: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare emergencyContact: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare infoSource: string | null
  @column.dateTime()
  declare interviewDate: DateTime | null
  @column()
  declare interviewer: string | null
  @column()
  declare livingWith: string | null
  @column()
  declare longTermGoals: string | null
  @column()
  declare majorChoice: string | null
  @column()
  declare notes: string | null
  @column()
  declare parentCommitments: any | null
  @column()
  declare reasonChoosingSchool: string | null
  @column()
  declare schoolOrigin: string
  @column()
  declare specialActivities: string | null
  @column()
  declare status: string
  @column()
  declare studentName: string
  @column()
  declare technicalScore: number | null
  @column()
  declare totalScore: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare violationAgreement: boolean | null
}

export class MajorSchema extends BaseModel {
  static $columns = ['code', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = MajorSchema.$columns
  @column()
  declare code: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SettingSchema extends BaseModel {
  static $columns = ['createdAt', 'key', 'updatedAt', 'value'] as const
  $columns = SettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare key: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare value: string | null
}

export class StudentSchema extends BaseModel {
  static $columns = ['class', 'createdAt', 'id', 'majorCode', 'name', 'nisn', 'status', 'updatedAt', 'userId'] as const
  $columns = StudentSchema.$columns
  @column()
  declare class: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare majorCode: string | null
  @column()
  declare name: string
  @column()
  declare nisn: string
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'role', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare role: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
